plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Home
markdown: GFM
url: "https://ronitrojasara.github.io/"
background-image: url('/webmage.svg')
